### ISSUE TITLE
ULM is not UML

### ISSUE THREAD

**Issue by mdevoldere** [titibrown/DWWM-2005#2]
ULM = Ultra Léger Motorisé
UML = Unified Modeling Language

Si on observe le répertoire "02 ulm", peut-être faudrait-il le renommer ?

**Comment by titibrown** [comment]
Oui, j'ai constaté cela aussi , je trouvais cela comique mais j'ai bien compris la différence merci :) Je suis en train de refaire mon git .

**Comment by titibrown** [comment]
Je t'invites a te rendre sur mon Git afin de constater le changement du git en General ;)
